galaxy_info:
  role_name: wsl
  author: sjlex
  description: An Ansible role to configure wsl.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - wsl

dependencies: []
