---
- name: "Role: fish"
  tags:
    - fish
  when:
    - ansible_facts['distribution'] == 'Debian'
    - ansible_facts['distribution_major_version'] == "12" or
      ansible_facts['distribution_major_version'] == "11" or
      ansible_facts['distribution_major_version'] == "10"
  block:
    - name: "Install packages"
      ansible.builtin.include_role:
        name: "sjlex.collection.fish"
      vars:
        fisher_plugins:
          - sjlex/plain-prompt
          - jethrokuan/z
          - jethrokuan/fzf

    - name: "Configuration"
      ansible.builtin.include_tasks:
        file: configuration.yml
