galaxy_info:
  role_name: tmuxinator
  author: sjlex
  description: An Ansible role to configure tmuxinator.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - tmuxinator

dependencies: []
