galaxy_info:
  role_name: user
  author: sjlex
  description: An Ansible role to configure users.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - user

dependencies: []
