galaxy_info:
  role_name: tmux
  author: sjlex
  description: An Ansible role to configure tmux.
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
      - bookworm
      - bullseye
      - buster

  galaxy_tags:
    - tmux

dependencies: []
